package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Aeroporti generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "aeroporti", schema = "public")
public class Aeroporti implements java.io.Serializable
{


  private int id;
  private String sigprov;
  private String aeroporto;
  private String codiceaeroporto;


  public Aeroporti()
  {
  }


  public Aeroporti(int id)
  {
    this.id = id;
  }


  public Aeroporti(int id, String sigprov, String aeroporto, String codiceaeroporto)
  {
    this.id = id;
    this.sigprov = sigprov;
    this.aeroporto = aeroporto;
    this.codiceaeroporto = codiceaeroporto;
  }


  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }


  public void setId(int id)
  {
    this.id = id;
  }


  @Column(name = "sigprov", length = 2)
  public String getSigprov()
  {
    return this.sigprov;
  }


  public void setSigprov(String sigprov)
  {
    this.sigprov = sigprov;
  }


  @Column(name = "aeroporto", length = 30)
  public String getAeroporto()
  {
    return this.aeroporto;
  }


  public void setAeroporto(String aeroporto)
  {
    this.aeroporto = aeroporto;
  }


  @Column(name = "codiceaeroporto", length = 10)
  public String getCodiceaeroporto()
  {
    return this.codiceaeroporto;
  }


  public void setCodiceaeroporto(String codiceaeroporto)
  {
    this.codiceaeroporto = codiceaeroporto;
  }


}
