package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;
import javax.persistence.*;
import mic.organic.core.AbstractModel;
import mic.organic.gateway.Json;


/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "banners")//, uniqueConstraints = @UniqueConstraint(columnNames = "regione"))
public class Banners extends AbstractModel implements Json
{
//  private Tipologia tipologia;
//  private Regione regione;
  private String tipologia;
  private String regione;
  private byte[] bannersx;
  private byte[] bannerdx;
  private Date fromthe;
  private Date tothe;
  private String sponsor;
  private String filename;
  private Long size;
  private String link;


  public Banners()
  {
  }


  public Banners(String tipologia, String regione, byte[] bannersx, byte[] bannerdx, Date fromthe, Date tothe, String sponsor, String filename, Long size, String link)
  {
    this.tipologia = tipologia;
    this.regione = regione;
    this.bannersx = bannersx;
    this.bannerdx = bannerdx;
    this.fromthe = fromthe;
    this.tothe = tothe;
    this.sponsor = sponsor;
    this.filename = filename;
    this.size = size;
    this.link = link;
  }

  //@ManyToOne(fetch = FetchType.LAZY)
  //@JoinColumn(name="tipologia", referencedColumnName="nomeesteso")
  public String getTipologia()
  {
    return this.tipologia;
  }


  public void setTipologia(String tipologia)
  {
    this.tipologia = tipologia;
  }


  //@ManyToOne(fetch = FetchType.LAZY)
  //@JoinColumn(name="regione", referencedColumnName="nomeregione")
  public String getRegione()
  {
    return this.regione;
  }


  public void setRegione(String regione)
  {
    this.regione = regione;
  }


  @Column(name = "bannersx")
  public byte[] getBannersx()
  {
    return this.bannersx;
  }


  public void setBannersx(byte[] bannersx)
  {
    this.bannersx = bannersx;
  }


  @Column(name = "bannerdx")
  public byte[] getBannerdx()
  {
    return this.bannerdx;
  }


  public void setBannerdx(byte[] bannerdx)
  {
    this.bannerdx = bannerdx;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "fromthe", length = 13)
  public Date getFromthe()
  {
    return this.fromthe;
  }


  public void setFromthe(Date fromthe)
  {
    this.fromthe = fromthe;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "tothe", length = 13)
  public Date getTothe()
  {
    return this.tothe;
  }


  public void setTothe(Date tothe)
  {
    this.tothe = tothe;
  }


  @Column(name = "sponsor")
  public String getSponsor()
  {
    return this.sponsor;
  }


  public void setSponsor(String sponsor)
  {
    this.sponsor = sponsor;
  }


  @Column(name = "filename")
  public String getFilename()
  {
    return this.filename;
  }


  public void setFilename(String filename)
  {
    this.filename = filename;
  }


  @Column(name = "size")
  public Long getSize()
  {
    return this.size;
  }


  public void setSize(Long size)
  {
    this.size = size;
  }


  @Column(name = "link")
  public String getLink()
  {
    return this.link;
  }


  public void setLink(String link)
  {
    this.link = link;
  }


}
