package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Brochure generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "brochure", schema = "public")
public class Brochure implements java.io.Serializable
{


  private int idBrochure;
  private byte[] brochure;
  private Date uploadDate;
  private String fileTitle;
  private Integer idAziende;
  private Long size;


  public Brochure()
  {
  }


  public Brochure(int idBrochure)
  {
    this.idBrochure = idBrochure;
  }


  public Brochure(int idBrochure, byte[] brochure, Date uploadDate, String fileTitle, Integer idAziende, Long size)
  {
    this.idBrochure = idBrochure;
    this.brochure = brochure;
    this.uploadDate = uploadDate;
    this.fileTitle = fileTitle;
    this.idAziende = idAziende;
    this.size = size;
  }


  @Id
  @Column(name = "id_brochure", unique = true, nullable = false)
  public int getIdBrochure()
  {
    return this.idBrochure;
  }


  public void setIdBrochure(int idBrochure)
  {
    this.idBrochure = idBrochure;
  }


  @Column(name = "brochure")
  public byte[] getBrochure()
  {
    return this.brochure;
  }


  public void setBrochure(byte[] brochure)
  {
    this.brochure = brochure;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "upload_date", length = 13)
  public Date getUploadDate()
  {
    return this.uploadDate;
  }


  public void setUploadDate(Date uploadDate)
  {
    this.uploadDate = uploadDate;
  }


  @Column(name = "file_title")
  public String getFileTitle()
  {
    return this.fileTitle;
  }


  public void setFileTitle(String fileTitle)
  {
    this.fileTitle = fileTitle;
  }


  @Column(name = "id_aziende")
  public Integer getIdAziende()
  {
    return this.idAziende;
  }


  public void setIdAziende(Integer idAziende)
  {
    this.idAziende = idAziende;
  }


  @Column(name = "size")
  public Long getSize()
  {
    return this.size;
  }


  public void setSize(Long size)
  {
    this.size = size;
  }


}
