package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import mic.organic.core.AbstractModel;


/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name = "calendario")
public class Calendario extends AbstractModel
{
  //private int idCalendario;
  private String gennaio;
  private String febbraio;
  private String marzo;
  private String aprile;
  private String maggio;
  private String giugno;
  private String luglio;
  private String agosto;
  private String settembre;
  private String ottobre;
  private String novembre;
  private String dicembre;


  public Calendario()
  {
  }


  public Calendario(int idCalendario)
  {
    /*this.idCalendario = idCalendario;*/setId(idCalendario);
  }


  public Calendario(int idCalendario, String gennaio, String febbraio, String marzo, String aprile, String maggio, String giugno, String luglio,
      String agosto, String settembre, String ottobre, String novembre, String dicembre)
  {
    /*this.idCalendario = idCalendario;*/setId(idCalendario);
    this.gennaio = gennaio;
    this.febbraio = febbraio;
    this.marzo = marzo;
    this.aprile = aprile;
    this.maggio = maggio;
    this.giugno = giugno;
    this.luglio = luglio;
    this.agosto = agosto;
    this.settembre = settembre;
    this.ottobre = ottobre;
    this.novembre = novembre;
    this.dicembre = dicembre;
  }

/*
  @Id @GeneratedValue
  @Column(name = "id_calendario", unique = true, nullable = false)
  public int getIdCalendario()
  {
    return this.idCalendario;
  }


  public void setIdCalendario(int idCalendario)
  {
    this.idCalendario = idCalendario;
  }
*/

  @Column(name = "gennaio")
  public String getGennaio()
  {
    return this.gennaio;
  }


  public void setGennaio(String gennaio)
  {
    this.gennaio = gennaio;
  }


  @Column(name = "febbraio")
  public String getFebbraio()
  {
    return this.febbraio;
  }


  public void setFebbraio(String febbraio)
  {
    this.febbraio = febbraio;
  }


  @Column(name = "marzo")
  public String getMarzo()
  {
    return this.marzo;
  }


  public void setMarzo(String marzo)
  {
    this.marzo = marzo;
  }


  @Column(name = "aprile")
  public String getAprile()
  {
    return this.aprile;
  }


  public void setAprile(String aprile)
  {
    this.aprile = aprile;
  }


  @Column(name = "maggio")
  public String getMaggio()
  {
    return this.maggio;
  }


  public void setMaggio(String maggio)
  {
    this.maggio = maggio;
  }


  @Column(name = "giugno")
  public String getGiugno()
  {
    return this.giugno;
  }


  public void setGiugno(String giugno)
  {
    this.giugno = giugno;
  }


  @Column(name = "luglio")
  public String getLuglio()
  {
    return this.luglio;
  }


  public void setLuglio(String luglio)
  {
    this.luglio = luglio;
  }


  @Column(name = "agosto")
  public String getAgosto()
  {
    return this.agosto;
  }


  public void setAgosto(String agosto)
  {
    this.agosto = agosto;
  }


  @Column(name = "settembre")
  public String getSettembre()
  {
    return this.settembre;
  }


  public void setSettembre(String settembre)
  {
    this.settembre = settembre;
  }


  @Column(name = "ottobre")
  public String getOttobre()
  {
    return this.ottobre;
  }


  public void setOttobre(String ottobre)
  {
    this.ottobre = ottobre;
  }


  @Column(name = "novembre")
  public String getNovembre()
  {
    return this.novembre;
  }


  public void setNovembre(String novembre)
  {
    this.novembre = novembre;
  }


  @Column(name = "dicembre")
  public String getDicembre()
  {
    return this.dicembre;
  }


  public void setDicembre(String dicembre)
  {
    this.dicembre = dicembre;
  }

}
