package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

import mic.organic.core.AbstractModel;


/**
 * Caratteristiche generated by hbm2java
 */
@Entity
@Table(name = "caratteristiche", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "id_azienda_est"))
public class Caratteristiche  extends AbstractModel
{
  private Integer numcamere;
  private Integer numlettimin;
  private Integer numlettimax;
  private Float tariffamin;
  private String include;
  private String prenotazione;
  private Date dal;
  private Date al;
  private String camera;
  private String bagno;
  private String tavola;
  private String struttura;
  private Integer idAziendaEst;
  private String pagamento;
  private Short appartamenti;
  private String lingue;
  private Integer kmcapoluogo;
  private Integer kmcasello;
  private Integer kmaeroporto;
  private Integer kmstazione;
  private Integer mtmezzipubblici;
  private Integer numlettitot;
  private String autostrade;
  private String aeroporti;
  private String stazioni;
  private Integer scontodel;
  private String offerta;
  private String latitudine;
  private String longitudine;
  private Integer entrokm;
  private Integer duratamin;
  private String linguadescr;
  private String slogan1;
  private String slogan2;
  private String urlslogan1;
  private String urlslogan2;
  private String note;
  private String immagini;
  private BigDecimal prezzomedio;
  private String tab;
  private String descrizioneIta;
  private String descrizioneEng;
  private String descrizioneDeu;
  private String descrizioneFra;


  public Caratteristiche()
  {
  }


  public Caratteristiche(Integer numcamere, Integer numlettimin, Integer numlettimax, Float tariffamin, String include, String prenotazione, Date dal, Date al, String camera,
      String bagno, String tavola, String struttura, Integer idAziendaEst, String pagamento, Short appartamenti, String lingue, Integer kmcapoluogo, Integer kmcasello,
      Integer kmaeroporto, Integer kmstazione, Integer mtmezzipubblici, Integer numlettitot, String autostrade, String aeroporti, String stazioni, Integer scontodel, String offerta,
      String latitudine, String longitudine, Integer entrokm, Integer duratamin, String linguadescr, String slogan1, String slogan2, String urlslogan1, String urlslogan2, String note,
      String immagini, BigDecimal prezzomedio, String tab, String descrizioneIta, String descrizioneEng, String descrizioneDeu, String descrizioneFra)
  {
    this.numcamere = numcamere;
    this.numlettimin = numlettimin;
    this.numlettimax = numlettimax;
    this.tariffamin = tariffamin;
    this.include = include;
    this.prenotazione = prenotazione;
    this.dal = dal;
    this.al = al;
    this.camera = camera;
    this.bagno = bagno;
    this.tavola = tavola;
    this.struttura = struttura;
    this.idAziendaEst = idAziendaEst;
    this.pagamento = pagamento;
    this.appartamenti = appartamenti;
    this.lingue = lingue;
    this.kmcapoluogo = kmcapoluogo;
    this.kmcasello = kmcasello;
    this.kmaeroporto = kmaeroporto;
    this.kmstazione = kmstazione;
    this.mtmezzipubblici = mtmezzipubblici;
    this.numlettitot = numlettitot;
    this.autostrade = autostrade;
    this.aeroporti = aeroporti;
    this.stazioni = stazioni;
    this.scontodel = scontodel;
    this.offerta = offerta;
    this.latitudine = latitudine;
    this.longitudine = longitudine;
    this.entrokm = entrokm;
    this.duratamin = duratamin;
    this.linguadescr = linguadescr;
    this.slogan1 = slogan1;
    this.slogan2 = slogan2;
    this.urlslogan1 = urlslogan1;
    this.urlslogan2 = urlslogan2;
    this.note = note;
    this.immagini = immagini;
    this.prezzomedio = prezzomedio;
    this.tab = tab;
    this.descrizioneIta = descrizioneIta;
    this.descrizioneEng = descrizioneEng;
    this.descrizioneDeu = descrizioneDeu;
    this.descrizioneFra = descrizioneFra;
  }


  @Column(name = "numcamere")
  public Integer getNumcamere()
  {
    return this.numcamere;
  }


  public void setNumcamere(Integer numcamere)
  {
    this.numcamere = numcamere;
  }


  @Column(name = "numlettimin")
  public Integer getNumlettimin()
  {
    return this.numlettimin;
  }


  public void setNumlettimin(Integer numlettimin)
  {
    this.numlettimin = numlettimin;
  }


  @Column(name = "numlettimax")
  public Integer getNumlettimax()
  {
    return this.numlettimax;
  }


  public void setNumlettimax(Integer numlettimax)
  {
    this.numlettimax = numlettimax;
  }


  @Column(name = "tariffamin", precision = 8, scale = 8)
  public Float getTariffamin()
  {
    return this.tariffamin;
  }


  public void setTariffamin(Float tariffamin)
  {
    this.tariffamin = tariffamin;
  }


  @Column(name = "include", length = 40)
  public String getInclude()
  {
    return this.include;
  }


  public void setInclude(String include)
  {
    this.include = include;
  }


  @Column(name = "prenotazione", length = 40)
  public String getPrenotazione()
  {
    return this.prenotazione;
  }


  public void setPrenotazione(String prenotazione)
  {
    this.prenotazione = prenotazione;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "dal", length = 13)
  public Date getDal()
  {
    return this.dal;
  }


  public void setDal(Date dal)
  {
    this.dal = dal;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "al", length = 13)
  public Date getAl()
  {
    return this.al;
  }


  public void setAl(Date al)
  {
    this.al = al;
  }


  @Column(name = "camera")
  public String getCamera()
  {
    return this.camera;
  }


  public void setCamera(String camera)
  {
    this.camera = camera;
  }


  @Column(name = "bagno")
  public String getBagno()
  {
    return this.bagno;
  }


  public void setBagno(String bagno)
  {
    this.bagno = bagno;
  }


  @Column(name = "tavola")
  public String getTavola()
  {
    return this.tavola;
  }


  public void setTavola(String tavola)
  {
    this.tavola = tavola;
  }


  @Column(name = "struttura")
  public String getStruttura()
  {
    return this.struttura;
  }


  public void setStruttura(String struttura)
  {
    this.struttura = struttura;
  }


  @Column(name = "id_azienda_est", unique = true)
  public Integer getIdAziendaEst()
  {
    return this.idAziendaEst;
  }


  public void setIdAziendaEst(Integer idAziendaEst)
  {
    this.idAziendaEst = idAziendaEst;
  }


  @Column(name = "pagamento")
  public String getPagamento()
  {
    return this.pagamento;
  }


  public void setPagamento(String pagamento)
  {
    this.pagamento = pagamento;
  }


  @Column(name = "appartamenti")
  public Short getAppartamenti()
  {
    return this.appartamenti;
  }


  public void setAppartamenti(Short appartamenti)
  {
    this.appartamenti = appartamenti;
  }


  @Column(name = "lingue")
  public String getLingue()
  {
    return this.lingue;
  }


  public void setLingue(String lingue)
  {
    this.lingue = lingue;
  }


  @Column(name = "kmcapoluogo")
  public Integer getKmcapoluogo()
  {
    return this.kmcapoluogo;
  }


  public void setKmcapoluogo(Integer kmcapoluogo)
  {
    this.kmcapoluogo = kmcapoluogo;
  }


  @Column(name = "kmcasello")
  public Integer getKmcasello()
  {
    return this.kmcasello;
  }


  public void setKmcasello(Integer kmcasello)
  {
    this.kmcasello = kmcasello;
  }


  @Column(name = "kmaeroporto")
  public Integer getKmaeroporto()
  {
    return this.kmaeroporto;
  }


  public void setKmaeroporto(Integer kmaeroporto)
  {
    this.kmaeroporto = kmaeroporto;
  }


  @Column(name = "kmstazione")
  public Integer getKmstazione()
  {
    return this.kmstazione;
  }


  public void setKmstazione(Integer kmstazione)
  {
    this.kmstazione = kmstazione;
  }


  @Column(name = "mtmezzipubblici")
  public Integer getMtmezzipubblici()
  {
    return this.mtmezzipubblici;
  }


  public void setMtmezzipubblici(Integer mtmezzipubblici)
  {
    this.mtmezzipubblici = mtmezzipubblici;
  }


  @Column(name = "numlettitot")
  public Integer getNumlettitot()
  {
    return this.numlettitot;
  }


  public void setNumlettitot(Integer numlettitot)
  {
    this.numlettitot = numlettitot;
  }


  @Column(name = "autostrade")
  public String getAutostrade()
  {
    return this.autostrade;
  }


  public void setAutostrade(String autostrade)
  {
    this.autostrade = autostrade;
  }


  @Column(name = "aeroporti")
  public String getAeroporti()
  {
    return this.aeroporti;
  }


  public void setAeroporti(String aeroporti)
  {
    this.aeroporti = aeroporti;
  }


  @Column(name = "stazioni")
  public String getStazioni()
  {
    return this.stazioni;
  }


  public void setStazioni(String stazioni)
  {
    this.stazioni = stazioni;
  }


  @Column(name = "scontodel")
  public Integer getScontodel()
  {
    return this.scontodel;
  }


  public void setScontodel(Integer scontodel)
  {
    this.scontodel = scontodel;
  }


  @Column(name = "offerta", length = 7)
  public String getOfferta()
  {
    return this.offerta;
  }


  public void setOfferta(String offerta)
  {
    this.offerta = offerta;
  }


  @Column(name = "latitudine")
  public String getLatitudine()
  {
    return this.latitudine;
  }


  public void setLatitudine(String latitudine)
  {
    this.latitudine = latitudine;
  }


  @Column(name = "longitudine")
  public String getLongitudine()
  {
    return this.longitudine;
  }


  public void setLongitudine(String longitudine)
  {
    this.longitudine = longitudine;
  }


  @Column(name = "entrokm")
  public Integer getEntrokm()
  {
    return this.entrokm;
  }


  public void setEntrokm(Integer entrokm)
  {
    this.entrokm = entrokm;
  }


  @Column(name = "duratamin")
  public Integer getDuratamin()
  {
    return this.duratamin;
  }


  public void setDuratamin(Integer duratamin)
  {
    this.duratamin = duratamin;
  }


  @Column(name = "linguadescr", length = 20)
  public String getLinguadescr()
  {
    return this.linguadescr;
  }


  public void setLinguadescr(String linguadescr)
  {
    this.linguadescr = linguadescr;
  }


  @Column(name = "slogan1")
  public String getSlogan1()
  {
    return this.slogan1;
  }


  public void setSlogan1(String slogan1)
  {
    this.slogan1 = slogan1;
  }


  @Column(name = "slogan2")
  public String getSlogan2()
  {
    return this.slogan2;
  }


  public void setSlogan2(String slogan2)
  {
    this.slogan2 = slogan2;
  }


  @Column(name = "urlslogan1")
  public String getUrlslogan1()
  {
    return this.urlslogan1;
  }


  public void setUrlslogan1(String urlslogan1)
  {
    this.urlslogan1 = urlslogan1;
  }


  @Column(name = "urlslogan2")
  public String getUrlslogan2()
  {
    return this.urlslogan2;
  }


  public void setUrlslogan2(String urlslogan2)
  {
    this.urlslogan2 = urlslogan2;
  }


  @Column(name = "note")
  public String getNote()
  {
    return this.note;
  }


  public void setNote(String note)
  {
    this.note = note;
  }


  @Column(name = "immagini")
  public String getImmagini()
  {
    return this.immagini;
  }


  public void setImmagini(String immagini)
  {
    this.immagini = immagini;
  }


  @Column(name = "prezzomedio", precision = 8)
  public BigDecimal getPrezzomedio()
  {
    return this.prezzomedio;
  }


  public void setPrezzomedio(BigDecimal prezzomedio)
  {
    this.prezzomedio = prezzomedio;
  }


  @Column(name = "tab")
  public String getTab()
  {
    return this.tab;
  }


  public void setTab(String tab)
  {
    this.tab = tab;
  }


  @Column(name = "descrizione_ita")
  public String getDescrizioneIta()
  {
    return this.descrizioneIta;
  }


  public void setDescrizioneIta(String descrizioneIta)
  {
    this.descrizioneIta = descrizioneIta;
  }


  @Column(name = "descrizione_eng")
  public String getDescrizioneEng()
  {
    return this.descrizioneEng;
  }


  public void setDescrizioneEng(String descrizioneEng)
  {
    this.descrizioneEng = descrizioneEng;
  }


  @Column(name = "descrizione_deu")
  public String getDescrizioneDeu()
  {
    return this.descrizioneDeu;
  }


  public void setDescrizioneDeu(String descrizioneDeu)
  {
    this.descrizioneDeu = descrizioneDeu;
  }


  @Column(name = "descrizione_fra")
  public String getDescrizioneFra()
  {
    return this.descrizioneFra;
  }


  public void setDescrizioneFra(String descrizioneFra)
  {
    this.descrizioneFra = descrizioneFra;
  }


}
