package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * ComuneId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ComuneId implements java.io.Serializable
{


  private int id;
  private String provincia;
  private String comune;


  public ComuneId()
  {
  }


  public ComuneId(int id, String provincia, String comune)
  {
    this.id = id;
    this.provincia = provincia;
    this.comune = comune;
  }


  @Column(name = "id", nullable = false)
  public int getId()
  {
    return this.id;
  }


  public void setId(int id)
  {
    this.id = id;
  }


  @Column(name = "provincia", nullable = false, length = 30)
  public String getProvincia()
  {
    return this.provincia;
  }


  public void setProvincia(String provincia)
  {
    this.provincia = provincia;
  }


  @Column(name = "comune", nullable = false, length = 150)
  public String getComune()
  {
    return this.comune;
  }


  public void setComune(String comune)
  {
    this.comune = comune;
  }


  public boolean equals(Object other)
  {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ComuneId))
      return false;
    ComuneId castOther = (ComuneId) other;

    return (this.getId() == castOther.getId())
        && ((this.getProvincia() == castOther.getProvincia()) || (this.getProvincia() != null && castOther.getProvincia() != null && this.getProvincia().equals(castOther.getProvincia())))
        && ((this.getComune() == castOther.getComune()) || (this.getComune() != null && castOther.getComune() != null && this.getComune().equals(castOther.getComune())));
  }


  public int hashCode()
  {
    int result = 17;

    result = 37 * result + this.getId();
    result = 37 * result + (getProvincia() == null ? 0 : this.getProvincia().hashCode());
    result = 37 * result + (getComune() == null ? 0 : this.getComune().hashCode());
    return result;
  }


}
