package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Immagini generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "immagini", schema = "public")
public class Immagini implements java.io.Serializable
{


  private int id;
  private int idDatiaziende;
  private Integer width;
  private Integer height;
  private Date uploadDate;
  private String imageName;
  private byte[] imageFile;
  private String imageNumber;
  private Long imageSize;


  public Immagini()
  {
  }


  public Immagini(int id, int idDatiaziende)
  {
    this.id = id;
    this.idDatiaziende = idDatiaziende;
  }


  public Immagini(int id, int idDatiaziende, Integer width, Integer height, Date uploadDate, String imageName, byte[] imageFile, String imageNumber, Long imageSize)
  {
    this.id = id;
    this.idDatiaziende = idDatiaziende;
    this.width = width;
    this.height = height;
    this.uploadDate = uploadDate;
    this.imageName = imageName;
    this.imageFile = imageFile;
    this.imageNumber = imageNumber;
    this.imageSize = imageSize;
  }


  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }


  public void setId(int id)
  {
    this.id = id;
  }


  @Column(name = "id_datiaziende", nullable = false)
  public int getIdDatiaziende()
  {
    return this.idDatiaziende;
  }


  public void setIdDatiaziende(int idDatiaziende)
  {
    this.idDatiaziende = idDatiaziende;
  }


  @Column(name = "width")
  public Integer getWidth()
  {
    return this.width;
  }


  public void setWidth(Integer width)
  {
    this.width = width;
  }


  @Column(name = "height")
  public Integer getHeight()
  {
    return this.height;
  }


  public void setHeight(Integer height)
  {
    this.height = height;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "upload_date", length = 13)
  public Date getUploadDate()
  {
    return this.uploadDate;
  }


  public void setUploadDate(Date uploadDate)
  {
    this.uploadDate = uploadDate;
  }


  @Column(name = "image_name")
  public String getImageName()
  {
    return this.imageName;
  }


  public void setImageName(String imageName)
  {
    this.imageName = imageName;
  }


  @Column(name = "image_file")
  public byte[] getImageFile()
  {
    return this.imageFile;
  }


  public void setImageFile(byte[] imageFile)
  {
    this.imageFile = imageFile;
  }


  @Column(name = "image_number", length = 2)
  public String getImageNumber()
  {
    return this.imageNumber;
  }


  public void setImageNumber(String imageNumber)
  {
    this.imageNumber = imageNumber;
  }


  @Column(name = "image_size")
  public Long getImageSize()
  {
    return this.imageSize;
  }


  public void setImageSize(Long imageSize)
  {
    this.imageSize = imageSize;
  }


}
