package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import mic.organic.core.AbstractModel;


/**
 * Titolare generated by hbm2java
 */
@Entity
@Table(name = "titolare", uniqueConstraints = { @UniqueConstraint(columnNames = "id_azienda"), @UniqueConstraint(columnNames = "codicefiscale"),
    @UniqueConstraint(columnNames = "username") })
public class Titolare extends AbstractModel
{
  private String nome;
  private String cognome;

  private Date datadinascita;
  private String codicefiscale;
  private String partitaiva;
  private String username;
  private String password;
  private Integer idAzienda;
  private Date ultimoaccesso;
  private Integer giorno;
  private String mese;
  private BigDecimal anno;
  private Date dataiscrizione;
  private Boolean abbonato;
  private Date giornopagamento;


  public Titolare()
  {
  }


  public Titolare(String nome, String cognome, Date datadinascita, String codicefiscale, String partitaiva, String username, String password, Integer idAzienda, Date ultimoaccesso, Integer giorno, String mese,
      BigDecimal anno, Date dataiscrizione, Boolean abbonato, Date giornopagamento)
  {
    this.nome = nome;
    this.cognome = cognome;
    this.datadinascita = datadinascita;
    this.codicefiscale = codicefiscale;
    this.partitaiva = partitaiva;
    this.username = username;
    this.password = password;
    this.idAzienda = idAzienda;
    this.ultimoaccesso = ultimoaccesso;
    this.giorno = giorno;
    this.mese = mese;
    this.anno = anno;
    this.dataiscrizione = dataiscrizione;
    this.abbonato = abbonato;
    this.giornopagamento = giornopagamento;
  }


  @Column(name = "nome", nullable = false)
  public String getNome()
  {
    return this.nome;
  }


  public void setNome(String nome)
  {
    this.nome = nome;
  }


  @Column(name = "cognome", nullable = false)
  public String getCognome()
  {
    return this.cognome;
  }


  public void setCognome(String cognome)
  {
    this.cognome = cognome;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "datadinascita", length = 13)
  public Date getDatadinascita()
  {
    return this.datadinascita;
  }


  public void setDatadinascita(Date datadinascita)
  {
    this.datadinascita = datadinascita;
  }


  @Column(name = "codicefiscale", unique = true, length = 16)
  public String getCodicefiscale()
  {
    return this.codicefiscale;
  }


  public void setCodicefiscale(String codicefiscale)
  {
    this.codicefiscale = codicefiscale;
  }


  @Column(name = "partitaiva")
  public String getPartitaiva()
  {
    return this.partitaiva;
  }


  public void setPartitaiva(String partitaiva)
  {
    this.partitaiva = partitaiva;
  }


  @Column(name = "username", unique = true, length = 150)
  public String getUsername()
  {
    return this.username;
  }


  public void setUsername(String username)
  {
    this.username = username;
  }


  @Column(name = "password", length = 30)
  public String getPassword()
  {
    return this.password;
  }


  public void setPassword(String password)
  {
    this.password = password;
  }


  @Column(name = "id_azienda", unique = true)
  public Integer getIdAzienda()
  {
    return this.idAzienda;
  }


  public void setIdAzienda(Integer idAzienda)
  {
    this.idAzienda = idAzienda;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "ultimoaccesso", length = 13)
  public Date getUltimoaccesso()
  {
    return this.ultimoaccesso;
  }


  public void setUltimoaccesso(Date ultimoaccesso)
  {
    this.ultimoaccesso = ultimoaccesso;
  }


  @Column(name = "giorno")
  public Integer getGiorno()
  {
    return this.giorno;
  }


  public void setGiorno(Integer giorno)
  {
    this.giorno = giorno;
  }


  @Column(name = "mese", length = 20)
  public String getMese()
  {
    return this.mese;
  }


  public void setMese(String mese)
  {
    this.mese = mese;
  }


  @Column(name = "anno", precision = 131089, scale = 0)
  public BigDecimal getAnno()
  {
    return this.anno;
  }


  public void setAnno(BigDecimal anno)
  {
    this.anno = anno;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "dataiscrizione", length = 13)
  public Date getDataiscrizione()
  {
    return this.dataiscrizione;
  }


  public void setDataiscrizione(Date dataiscrizione)
  {
    this.dataiscrizione = dataiscrizione;
  }


  @Column(name = "abbonato")
  public Boolean getAbbonato()
  {
    return this.abbonato;
  }


  public void setAbbonato(Boolean abbonato)
  {
    this.abbonato = abbonato;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "giornopagamento", length = 13)
  public Date getGiornopagamento()
  {
    return this.giornopagamento;
  }


  public void setGiornopagamento(Date giornopagamento)
  {
    this.giornopagamento = giornopagamento;
  }


}
