package anna.alit.model;

// Generated Mar 17, 2010 6:53:18 PM by Hibernate Tools 3.3.0.GA


import java.math.BigDecimal;
import javax.persistence.*;

import mic.organic.core.AbstractModel;
import mic.organic.gateway.Json;


/**
 * Datiaziende generated by hbm2java
 */
@Entity
@Table(name = "datiaziende")
public class AziendeModel extends AbstractModel implements Json
{
  private String tipologia;
  private String sigla;
  private String comune;
  private String denominazione;
  private String indirizzo;
  private String telefono;
  private String telefono2;
  private String cellulare;
  private String cellulare2;
  private String fax;
  private String web;
  private String mail;
  private BigDecimal annofondazione;
  private String tipoesteso;
  private String zona;
  private String nzona;
  private String loco;
  private String civico;
  private String posizione; // TODO this is an array
  private String costruzione;
  private BigDecimal cap;
  private String fax2;
  private String youtube;
  private String flickr;
  private String myspace;
  private String facebook;
  private String ipnum;
  private String iplett;
  private Integer contaclick;
  private Integer punteggio;
  private String skype;
  private Boolean responsabilita;
  private Boolean notified;


  public AziendeModel()
  {
    super();
  }


  public AziendeModel(String tipologia, String sigla, String comune, String denominazione, String mail)
  {
    this();

    this.tipologia = tipologia;
    this.sigla = sigla;
    this.comune = comune;
    this.denominazione = denominazione;

    this.mail = mail;
  }


  public AziendeModel(String tipologia, String sigla, String comune, String denominazione/*AziendeId id*/, String indirizzo, String telefono, String telefono2, String cellulare, String cellulare2, String fax, String web, String mail, BigDecimal annofondazione,
      String tipoesteso, String zona, String nzona, String loco, String civico, String/*[]*/ posizione, String costruzione, BigDecimal cap, String fax2, String youtube, String flickr, String myspace,
      String facebook, String ipnum, String iplett, Integer contaclick, Integer punteggio, String skype, Boolean responsabilita, Boolean notified)
  {
    this.indirizzo = indirizzo;
    this.telefono = telefono;
    this.telefono2 = telefono2;
    this.cellulare = cellulare;
    this.cellulare2 = cellulare2;
    this.fax = fax;
    this.web = web;
    this.mail = mail;
    this.annofondazione = annofondazione;
    this.tipoesteso = tipoesteso;
    this.zona = zona;
    this.nzona = nzona;
    this.loco = loco;
    this.civico = civico;
    this.posizione = posizione;
    this.costruzione = costruzione;
    this.cap = cap;
    this.fax2 = fax2;
    this.youtube = youtube;
    this.flickr = flickr;
    this.myspace = myspace;
    this.facebook = facebook;
    this.ipnum = ipnum;
    this.iplett = iplett;
    this.contaclick = contaclick;
    this.punteggio = punteggio;
    this.skype = skype;
    this.responsabilita = responsabilita;
    this.notified = notified;
  }


/*
  @EmbeddedId
  @AttributeOverrides( { @AttributeOverride(name = "id", column = @Column(name = "id", unique = true, nullable = false)),
      @AttributeOverride(name = "tipologia", column = @Column(name = "tipologia", nullable = false, length = 2)),
      @AttributeOverride(name = "sigla", column = @Column(name = "sigla", nullable = false, length = 2)),
      @AttributeOverride(name = "comune", column = @Column(name = "comune", nullable = false, length = 150)),
      @AttributeOverride(name = "denominazione", column = @Column(name = "denominazione", nullable = false, length = 150)) })
*/


  @Column(name = "tipologia", nullable = false, length = 2)
  public String getTipologia()
  {
    return this.tipologia;
  }


  public void setTipologia(String tipologia)
  {
    this.tipologia = tipologia;
  }


  /*
   * , length = 2, columnDefinition="bpchar"
   */
  @Column(name = "sigla", nullable = false)
  public String getSigla()
  {
    return this.sigla;
  }


  public void setSigla(String sigla)
  {
    this.sigla = sigla;
  }


  @Column(name = "comune", nullable = false, length = 150)
  public String getComune()
  {
    return this.comune;
  }


  public void setComune(String comune)
  {
    this.comune = comune;
  }


  @Column(name = "denominazione", nullable = false, length = 150)
  public String getDenominazione()
  {
    return this.denominazione;
  }


  public void setDenominazione(String denominazione)
  {
    this.denominazione = denominazione;
  }



  @Column(name = "indirizzo")
  public String getIndirizzo()
  {
    return this.indirizzo;
  }


  public void setIndirizzo(String indirizzo)
  {
    this.indirizzo = indirizzo;
  }


  @Column(name = "telefono", length = 60)
  public String getTelefono()
  {
    return this.telefono;
  }


  public void setTelefono(String telefono)
  {
    this.telefono = telefono;
  }


  @Column(name = "telefono2", length = 50)
  public String getTelefono2()
  {
    return this.telefono2;
  }


  public void setTelefono2(String telefono2)
  {
    this.telefono2 = telefono2;
  }


  @Column(name = "cellulare", length = 60)
  public String getCellulare()
  {
    return this.cellulare;
  }


  public void setCellulare(String cellulare)
  {
    this.cellulare = cellulare;
  }


  @Column(name = "cellulare2", length = 50)
  public String getCellulare2()
  {
    return this.cellulare2;
  }


  public void setCellulare2(String cellulare2)
  {
    this.cellulare2 = cellulare2;
  }


  @Column(name = "fax", length = 50)
  public String getFax()
  {
    return this.fax;
  }


  public void setFax(String fax)
  {
    this.fax = fax;
  }


  @Column(name = "web", length = 150)
  public String getWeb()
  {
    return this.web;
  }


  public void setWeb(String web)
  {
    this.web = web;
  }


  @Column(name = "mail", nullable = true)
  public String getMail()
  {
    return this.mail;
  }


  public void setMail(String mail)
  {
    this.mail = mail;
  }


  @Column(name = "annofondazione", precision = 131089, scale = 0)
  public BigDecimal getAnnofondazione()
  {
    return this.annofondazione;
  }


  public void setAnnofondazione(BigDecimal annofondazione)
  {
    this.annofondazione = annofondazione;
  }


  @Column(name = "tipoesteso", length = 30)
  public String getTipoesteso()
  {
    return this.tipoesteso;
  }


  public void setTipoesteso(String tipoesteso)
  {
    this.tipoesteso = tipoesteso;
  }


  @Column(name = "zona", length = 100)
  public String getZona()
  {
    return this.zona;
  }


  public void setZona(String zona)
  {
    this.zona = zona;
  }


  @Column(name = "nzona", length = 100)
  public String getNzona()
  {
    return this.nzona;
  }


  public void setNzona(String nzona)
  {
    this.nzona = nzona;
  }


  @Column(name = "loco", length = 100)
  public String getLoco()
  {
    return this.loco;
  }


  public void setLoco(String loco)
  {
    this.loco = loco;
  }


  @Column(name = "civico", length = 30)
  public String getCivico()
  {
    return this.civico;
  }


  public void setCivico(String civico)
  {
    this.civico = civico;
  }

  @Column(name = "posizione")
  public String getPosizione()
  {
    return this.posizione;
  }


  public void setPosizione(String posizione)
  {
    this.posizione = posizione;
  }


  @Column(name = "costruzione")
  public String getCostruzione()
  {
    return this.costruzione;
  }


  public void setCostruzione(String costruzione)
  {
    this.costruzione = costruzione;
  }


  @Column(name = "cap", precision = 131089, scale = 0)
  public BigDecimal getCap()
  {
    return this.cap;
  }


  public void setCap(BigDecimal cap)
  {
    this.cap = cap;
  }


  @Column(name = "fax2", length = 50)
  public String getFax2()
  {
    return this.fax2;
  }


  public void setFax2(String fax2)
  {
    this.fax2 = fax2;
  }


  @Column(name = "youtube")
  public String getYoutube()
  {
    return this.youtube;
  }


  public void setYoutube(String youtube)
  {
    this.youtube = youtube;
  }


  @Column(name = "flickr")
  public String getFlickr()
  {
    return this.flickr;
  }


  public void setFlickr(String flickr)
  {
    this.flickr = flickr;
  }


  @Column(name = "myspace")
  public String getMyspace()
  {
    return this.myspace;
  }


  public void setMyspace(String myspace)
  {
    this.myspace = myspace;
  }


  @Column(name = "facebook")
  public String getFacebook()
  {
    return this.facebook;
  }


  public void setFacebook(String facebook)
  {
    this.facebook = facebook;
  }


  @Column(name = "ipnum")
  public String getIpnum()
  {
    return this.ipnum;
  }


  public void setIpnum(String ipnum)
  {
    this.ipnum = ipnum;
  }


  @Column(name = "iplett")
  public String getIplett()
  {
    return this.iplett;
  }


  public void setIplett(String iplett)
  {
    this.iplett = iplett;
  }


  @Column(name = "contaclick")
  public Integer getContaclick()
  {
    return this.contaclick;
  }


  public void setContaclick(Integer contaclick)
  {
    this.contaclick = contaclick;
  }


  @Column(name = "punteggio")
  public Integer getPunteggio()
  {
    return this.punteggio;
  }


  public void setPunteggio(Integer punteggio)
  {
    this.punteggio = punteggio;
  }


  @Column(name = "skype")
  public String getSkype()
  {
    return this.skype;
  }


  public void setSkype(String skype)
  {
    this.skype = skype;
  }


  @Column(name = "responsabilita")
  public Boolean getResponsabilita()
  {
    return this.responsabilita;
  }


  public void setResponsabilita(Boolean responsabilita)
  {
    this.responsabilita = responsabilita;
  }


  @Column(name = "notified")
  public Boolean getNotified()
  {
    return notified;
  }


  public void setNotified(Boolean notified)
  {
    this.notified = notified;
  }




}
