package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * Caselliautostrade generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "caselliautostrade", schema = "public")
public class Caselliautostrade implements java.io.Serializable
{


  private CaselliautostradeId id;
  private String uscita;
  private String sigprov;


  public Caselliautostrade()
  {
  }


  public Caselliautostrade(CaselliautostradeId id)
  {
    this.id = id;
  }


  public Caselliautostrade(CaselliautostradeId id, String uscita, String sigprov)
  {
    this.id = id;
    this.uscita = uscita;
    this.sigprov = sigprov;
  }


  @EmbeddedId
  @AttributeOverrides( { @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
      @AttributeOverride(name = "autostrada", column = @Column(name = "autostrada", nullable = false, length = 50)) })
  public CaselliautostradeId getId()
  {
    return this.id;
  }


  public void setId(CaselliautostradeId id)
  {
    this.id = id;
  }


  @Column(name = "uscita", length = 100)
  public String getUscita()
  {
    return this.uscita;
  }


  public void setUscita(String uscita)
  {
    this.uscita = uscita;
  }


  @Column(name = "sigprov", length = 2)
  public String getSigprov()
  {
    return this.sigprov;
  }


  public void setSigprov(String sigprov)
  {
    this.sigprov = sigprov;
  }


}
