package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * Comune generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "comune", schema = "public")
public class Comune implements java.io.Serializable
{


  private ComuneId id;
  private String webistituzionale;
  private String wwwcomuniitaliani;
  private String wwwilmeteo;
  private String siglaprovincia;


  public Comune()
  {
  }


  public Comune(ComuneId id)
  {
    this.id = id;
  }


  public Comune(ComuneId id, String webistituzionale, String wwwcomuniitaliani, String wwwilmeteo, String siglaprovincia)
  {
    this.id = id;
    this.webistituzionale = webistituzionale;
    this.wwwcomuniitaliani = wwwcomuniitaliani;
    this.wwwilmeteo = wwwilmeteo;
    this.siglaprovincia = siglaprovincia;
  }


  @EmbeddedId
  @AttributeOverrides( { @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
      @AttributeOverride(name = "provincia", column = @Column(name = "provincia", nullable = false, length = 30)),
      @AttributeOverride(name = "comune", column = @Column(name = "comune", nullable = false, length = 150)) })
  public ComuneId getId()
  {
    return this.id;
  }


  public void setId(ComuneId id)
  {
    this.id = id;
  }


  @Column(name = "webistituzionale", length = 150)
  public String getWebistituzionale()
  {
    return this.webistituzionale;
  }


  public void setWebistituzionale(String webistituzionale)
  {
    this.webistituzionale = webistituzionale;
  }


  @Column(name = "wwwcomuniitaliani", length = 150)
  public String getWwwcomuniitaliani()
  {
    return this.wwwcomuniitaliani;
  }


  public void setWwwcomuniitaliani(String wwwcomuniitaliani)
  {
    this.wwwcomuniitaliani = wwwcomuniitaliani;
  }


  @Column(name = "wwwilmeteo", length = 150)
  public String getWwwilmeteo()
  {
    return this.wwwilmeteo;
  }


  public void setWwwilmeteo(String wwwilmeteo)
  {
    this.wwwilmeteo = wwwilmeteo;
  }


  @Column(name = "siglaprovincia")
  public String getSiglaprovincia()
  {
    return this.siglaprovincia;
  }


  public void setSiglaprovincia(String siglaprovincia)
  {
    this.siglaprovincia = siglaprovincia;
  }


}
