package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Distretto generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "distretto", schema = "public")
public class Distretto implements java.io.Serializable
{


  private int id;
  private String distretto;
  private String comune;
  private String prov;


  public Distretto()
  {
  }


  public Distretto(int id, String distretto)
  {
    this.id = id;
    this.distretto = distretto;
  }


  public Distretto(int id, String distretto, String comune, String prov)
  {
    this.id = id;
    this.distretto = distretto;
    this.comune = comune;
    this.prov = prov;
  }


  @Id
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }


  public void setId(int id)
  {
    this.id = id;
  }


  @Column(name = "distretto", nullable = false)
  public String getDistretto()
  {
    return this.distretto;
  }


  public void setDistretto(String distretto)
  {
    this.distretto = distretto;
  }


  @Column(name = "comune")
  public String getComune()
  {
    return this.comune;
  }


  public void setComune(String comune)
  {
    this.comune = comune;
  }


  @Column(name = "prov", length = 2)
  public String getProv()
  {
    return this.prov;
  }


  public void setProv(String prov)
  {
    this.prov = prov;
  }


}
