package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Emailconnection generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "emailconnection", schema = "public")
public class Emailconnection implements java.io.Serializable
{


  private EmailconnectionId id;
  private String emailUser;
  private String emailAzienda;
  private Date dataSpedizione;
  private String denominazione;


  public Emailconnection()
  {
  }


  public Emailconnection(EmailconnectionId id)
  {
    this.id = id;
  }


  public Emailconnection(EmailconnectionId id, String emailUser, String emailAzienda, Date dataSpedizione, String denominazione)
  {
    this.id = id;
    this.emailUser = emailUser;
    this.emailAzienda = emailAzienda;
    this.dataSpedizione = dataSpedizione;
    this.denominazione = denominazione;
  }


  @EmbeddedId
  @AttributeOverrides( { @AttributeOverride(name = "idAzienda", column = @Column(name = "id_azienda", nullable = false)),
      @AttributeOverride(name = "dataCreazione", column = @Column(name = "data_creazione", nullable = false, length = 29)) })
  public EmailconnectionId getId()
  {
    return this.id;
  }


  public void setId(EmailconnectionId id)
  {
    this.id = id;
  }


  @Column(name = "email_user")
  public String getEmailUser()
  {
    return this.emailUser;
  }


  public void setEmailUser(String emailUser)
  {
    this.emailUser = emailUser;
  }


  @Column(name = "email_azienda")
  public String getEmailAzienda()
  {
    return this.emailAzienda;
  }


  public void setEmailAzienda(String emailAzienda)
  {
    this.emailAzienda = emailAzienda;
  }


  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "data_spedizione", length = 29)
  public Date getDataSpedizione()
  {
    return this.dataSpedizione;
  }


  public void setDataSpedizione(Date dataSpedizione)
  {
    this.dataSpedizione = dataSpedizione;
  }


  @Column(name = "denominazione")
  public String getDenominazione()
  {
    return this.denominazione;
  }


  public void setDenominazione(String denominazione)
  {
    this.denominazione = denominazione;
  }


}
