package anna.alit.model;

// Generated Mar 17, 2010 6:53:44 PM by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * Provincia generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "provincia", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nomeesteso"))
public class Provincia implements java.io.Serializable
{


  private String sigla;
  private String nomeesteso;
  private String regione;
  private String limitrofa1;
  private String limitrofa2;
  private String limitrofa3;
  private String limitrofa4;
  private String limitrofa5;
  private String limitrofa6;
  private String limitrofa7;
  private String limitrofa8;
  private String sitoprovincia;


  public Provincia()
  {
  }


  public Provincia(String sigla)
  {
    this.sigla = sigla;
  }


  public Provincia(String sigla, String nomeesteso, String regione, String limitrofa1, String limitrofa2, String limitrofa3, String limitrofa4, String limitrofa5, String limitrofa6,
      String limitrofa7, String limitrofa8, String sitoprovincia)
  {
    this.sigla = sigla;
    this.nomeesteso = nomeesteso;
    this.regione = regione;
    this.limitrofa1 = limitrofa1;
    this.limitrofa2 = limitrofa2;
    this.limitrofa3 = limitrofa3;
    this.limitrofa4 = limitrofa4;
    this.limitrofa5 = limitrofa5;
    this.limitrofa6 = limitrofa6;
    this.limitrofa7 = limitrofa7;
    this.limitrofa8 = limitrofa8;
    this.sitoprovincia = sitoprovincia;
  }


  @Id
  @Column(name = "sigla", unique = true, nullable = false, length = 2)
  public String getSigla()
  {
    return this.sigla;
  }


  public void setSigla(String sigla)
  {
    this.sigla = sigla;
  }


  @Column(name = "nomeesteso", unique = true)
  public String getNomeesteso()
  {
    return this.nomeesteso;
  }


  public void setNomeesteso(String nomeesteso)
  {
    this.nomeesteso = nomeesteso;
  }


  @Column(name = "regione")
  public String getRegione()
  {
    return this.regione;
  }


  public void setRegione(String regione)
  {
    this.regione = regione;
  }


  @Column(name = "limitrofa1", length = 2)
  public String getLimitrofa1()
  {
    return this.limitrofa1;
  }


  public void setLimitrofa1(String limitrofa1)
  {
    this.limitrofa1 = limitrofa1;
  }


  @Column(name = "limitrofa2", length = 2)
  public String getLimitrofa2()
  {
    return this.limitrofa2;
  }


  public void setLimitrofa2(String limitrofa2)
  {
    this.limitrofa2 = limitrofa2;
  }


  @Column(name = "limitrofa3", length = 2)
  public String getLimitrofa3()
  {
    return this.limitrofa3;
  }


  public void setLimitrofa3(String limitrofa3)
  {
    this.limitrofa3 = limitrofa3;
  }


  @Column(name = "limitrofa4", length = 2)
  public String getLimitrofa4()
  {
    return this.limitrofa4;
  }


  public void setLimitrofa4(String limitrofa4)
  {
    this.limitrofa4 = limitrofa4;
  }


  @Column(name = "limitrofa5", length = 2)
  public String getLimitrofa5()
  {
    return this.limitrofa5;
  }


  public void setLimitrofa5(String limitrofa5)
  {
    this.limitrofa5 = limitrofa5;
  }


  @Column(name = "limitrofa6", length = 2)
  public String getLimitrofa6()
  {
    return this.limitrofa6;
  }


  public void setLimitrofa6(String limitrofa6)
  {
    this.limitrofa6 = limitrofa6;
  }


  @Column(name = "limitrofa7", length = 2)
  public String getLimitrofa7()
  {
    return this.limitrofa7;
  }


  public void setLimitrofa7(String limitrofa7)
  {
    this.limitrofa7 = limitrofa7;
  }


  @Column(name = "limitrofa8", length = 2)
  public String getLimitrofa8()
  {
    return this.limitrofa8;
  }


  public void setLimitrofa8(String limitrofa8)
  {
    this.limitrofa8 = limitrofa8;
  }


  @Column(name = "sitoprovincia")
  public String getSitoprovincia()
  {
    return this.sitoprovincia;
  }


  public void setSitoprovincia(String sitoprovincia)
  {
    this.sitoprovincia = sitoprovincia;
  }


}
