package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Set;
import javax.persistence.*;
import mic.organic.core.AbstractModel;


/**
 * Regione generated by hbm2java
 */
@Entity
@Table(name = "regione", uniqueConstraints = @UniqueConstraint(columnNames = "nomeregione"))
public class Regione extends AbstractModel
{
  private String nomeregione;
  private String sito;
  //private Set<Banners> banners = new HashSet<Banners>(0);


  public Regione()
  {
  }


  public Regione(String nomeregione, String sito, Set<Banners> bannerses)
  {
    this.nomeregione = nomeregione;
    this.sito = sito;
    //this.banners = banners;
  }

  @Column(name = "nomeregione", unique = true, length = 30)
  public String getNomeregione()
  {
    return this.nomeregione;
  }


  public void setNomeregione(String nomeregione)
  {
    this.nomeregione = nomeregione;
  }


  @Column(name = "sito", length = 100)
  public String getSito()
  {
    return this.sito;
  }


  public void setSito(String sito)
  {
    this.sito = sito;
  }


//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "regione")
//  public Set<Banners> getBanners()
//  {
//    return this.banners;
//  }
//
//
//  public void setBanners(Set<Banners> banners)
//  {
//    this.banners = banners;
//  }


}
