package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Segnalazioni generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "segnalazioni", schema = "public")
public class Segnalazioni implements java.io.Serializable
{


  private int id;
  private String tipo;
  private String nome;
  private String descrizione2;
  private String categoria;
  private String regione;
  private String prov;
  private String comu;
  private Date dal;
  private Date al;
  private Integer idazienda;
  private String settore;
  private Date datapubblicazione;


  public Segnalazioni()
  {
  }


  public Segnalazioni(int id)
  {
    this.id = id;
  }


  public Segnalazioni(int id, String tipo, String nome, String descrizione2, String categoria, String regione, String prov, String comu, Date dal, Date al, Integer idazienda, String settore,
      Date datapubblicazione)
  {
    this.id = id;
    this.tipo = tipo;
    this.nome = nome;
    this.descrizione2 = descrizione2;
    this.categoria = categoria;
    this.regione = regione;
    this.prov = prov;
    this.comu = comu;
    this.dal = dal;
    this.al = al;
    this.idazienda = idazienda;
    this.settore = settore;
    this.datapubblicazione = datapubblicazione;
  }


  @Id @GeneratedValue
  @Column(name = "id", unique = true, nullable = false)
  public int getId()
  {
    return this.id;
  }


  public void setId(int id)
  {
    this.id = id;
  }


  @Column(name = "tipo")
  public String getTipo()
  {
    return this.tipo;
  }


  public void setTipo(String tipo)
  {
    this.tipo = tipo;
  }


  @Column(name = "nome")
  public String getNome()
  {
    return this.nome;
  }


  public void setNome(String nome)
  {
    this.nome = nome;
  }


  @Column(name = "descrizione2")
  public String getDescrizione2()
  {
    return this.descrizione2;
  }


  public void setDescrizione2(String descrizione2)
  {
    this.descrizione2 = descrizione2;
  }


  @Column(name = "categoria")
  public String getCategoria()
  {
    return this.categoria;
  }


  public void setCategoria(String categoria)
  {
    this.categoria = categoria;
  }


  @Column(name = "regione")
  public String getRegione()
  {
    return this.regione;
  }


  public void setRegione(String regione)
  {
    this.regione = regione;
  }


  @Column(name = "prov", length = 2)
  public String getProv()
  {
    return this.prov;
  }


  public void setProv(String prov)
  {
    this.prov = prov;
  }


  @Column(name = "comu")
  public String getComu()
  {
    return this.comu;
  }


  public void setComu(String comu)
  {
    this.comu = comu;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "dal", length = 13)
  public Date getDal()
  {
    return this.dal;
  }


  public void setDal(Date dal)
  {
    this.dal = dal;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "al", length = 13)
  public Date getAl()
  {
    return this.al;
  }


  public void setAl(Date al)
  {
    this.al = al;
  }


  @Column(name = "idazienda")
  public Integer getIdazienda()
  {
    return this.idazienda;
  }


  public void setIdazienda(Integer idazienda)
  {
    this.idazienda = idazienda;
  }


  @Column(name = "settore")
  public String getSettore()
  {
    return this.settore;
  }


  public void setSettore(String settore)
  {
    this.settore = settore;
  }


  @Temporal(TemporalType.DATE)
  @Column(name = "datapubblicazione", length = 13)
  public Date getDatapubblicazione()
  {
    return this.datapubblicazione;
  }


  public void setDatapubblicazione(Date datapubblicazione)
  {
    this.datapubblicazione = datapubblicazione;
  }


}
