package anna.alit.model;

// Generated Mar 17, 2010 6:53:04 PM by Hibernate Tools 3.3.0.GA


import java.util.Set;
import javax.persistence.*;


/**
 * Tipologia generated by hbm2java
 */
@Entity
@Table(name = "tipologia", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nomeesteso"))
public class Tipologia
{


  private String codice;
  private String nomeesteso;
  private String descrizione;
//  private Set<Banners> banners = new HashSet<Banners>(0);


  public Tipologia()
  {
  }


  public Tipologia(String codice)
  {
    this.codice = codice;
  }


  public Tipologia(String codice, String nomeesteso, String descrizione, Set<Banners> banners)
  {
    this.codice = codice;
    this.nomeesteso = nomeesteso;
    this.descrizione = descrizione;
//    this.banners = banners;
  }


  @Id @GeneratedValue
  @Column(name = "codice", unique = true, nullable = false, length = 2)
  public String getCodice()
  {
    return this.codice;
  }


  public void setCodice(String codice)
  {
    this.codice = codice;
  }


  @Column(name = "nomeesteso", unique = true)
  public String getNomeesteso()
  {
    return this.nomeesteso;
  }


  public void setNomeesteso(String nomeesteso)
  {
    this.nomeesteso = nomeesteso;
  }


  @Column(name = "descrizione")
  public String getDescrizione()
  {
    return this.descrizione;
  }


  public void setDescrizione(String descrizione)
  {
    this.descrizione = descrizione;
  }


//  @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipologia")
//  public Set<Banners> getBanners()
//  {
//    return this.banners;
//  }


//  public void setBanners(Set<Banners> banners)
//  {
//    this.banners = banners;
//  }


}
